// ui/src/components/ArticleList.svelte
<script>
  import { onMount } from "svelte";
  import ArticleCard from "./ArticleCard.svelte";

  let articles = []; // TODO: type this
  let isLoaded = false;

  onMount(async () => {
    try {
      const res = await fetch('http://localhost:3001/');
      articles = await res.json();
    } catch (e) {
      console.error(e);
    }
    isLoaded = true;
    console.log("articles: ", articles);
    console.log("first id: ", articles[0].id)
  });
</script>


{#if isLoaded}
  {#each articles as a}
    <ArticleCard imgUrl={a.data.imgUrl} id={a.id} />
  {/each}
{:else}
  <!-- Might be cool to have a loading card -->
  <ArticleCard />
  <ArticleCard />
  <ArticleCard />
{/if}

// ui/src/views/Home/components/ArticleList.vue
<template>
  <div>
    <Loading :loading="store.state.loading" />
    <ul class="article-list">
      <ArticleCard 
        v-for="a in articles" 
        :key=a.name
        :id=a.id
        :title=a.title
        :subtitle=a.subtitle
      />
    </ul>
  </div>
</template>

<script>
import store from "../../../store";
import ArticleCard from './ArticleCard.vue';
import Loading from '../../../components/Loading';

export default {
  name: "ArticleList",
  components: {
    ArticleCard,
    Loading,
  },
  data() {
    console.log("store: ", store)
    return {
      articles: [],
      store: store
    }
  },
  async created() {
    try {
      this.store.setLoading(true);
      this.articles = (await (await fetch("http://localhost:3001/")).json())
        .map(a => ({
          id: a.id,
          subtitle: a.data.subtitle,
          title: a.data.title
        }));
      this.store.setLoading(false);
    } catch (err) {
      console.error(err);
    }
  }
}
</script>
